inoremap jk <ESC>
let mapleader = "\<Space>"

filetype off " required
autocmd filetype crontab setlocal nobackup nowritebackup " make crontab -e work

set encoding=utf-8

" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/vundle.vim
" run vim, and then do :PluginInstall
set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tomasr/molokai'
Plugin 'slim-template/vim-slim.git'
Plugin 'mxw/vim-jsx'
Plugin 'editorconfig/editorconfig-vim'
call vundle#end()

filetype plugin indent on

set tabstop=2
set shiftwidth=2
set expandtab

set clipboard=unnamed " make copy and paste work properly
set guifont=Menlo:h14
set hlsearch
set number
set spell
set wildmode=full

syntax enable

let g:jsx_ext_required = 0 " allow JSX in normal JS files
let g:rehash256 = 1

colorscheme molokai
